### ISSUE TITLE
Turning Autos switch on Freezes/Crashes game

### ISSUE THREAD

**Issue by SrryIChoked** [dexman545/Fabric-Autoswitch#28]
I'm playing on a paper server when this happens. I can turn it off just fine but when I press R to enable my game will freeze and more often than not it will crash. I find that the longer I have it turned off before turning it on the worse the freeze/crash is. If it is off for less than 30 sec I have no freezing issues.

(I just realized I change the config file and fixed my minor block issues except for sugar cane.) Another minor issue is some of the switching options. When I hit the ender dragon it will switch away from my weapon. Whenever I break any farm block (wheat, carrot, beetroot, sugar cane) it switches to my ax or other tools. If it could stay at just my fist that would be nice.

**Comment by dexman545** [comment]
What version of AS are you using?

Ender dragon fixed in 3.0.0-alpha.8 (can find on Modrinth)

If you add sugar cane to the config, you can configure how AS picks the tool.

Sugar cane and crop blocks all use the plant material. Adding them to the config you can also disable switching for them. I avoid doing so by default as I want users to be able to easily configure multiple blocks at once, and the override system is per target.

**Comment by dexman545** [comment]
Fixed in 3.0.0-alpha.9
