### ISSUE TITLE
Fix switching to wrong tool

### ISSUE THREAD

**Issue by wiktormalyska** [dexman545/Fabric-Autoswitch#59]
make it so bamboo and leaves will always be broken by hand

**Comment by dexman545** [comment]
Version?
What tool is it selecting?

**Comment by wiktormalyska** [comment]
7.0.0 alpha1
It's selecting sword, then axe, also haybales are not auto selecting into hoe

**Comment by dexman545** [comment]
Ok, so some issues are to be expected as v7 gets finalized due to Materials being removed and some changes to tool selection logic.

For bamboo, it instabreaks with swords, and will break faster with an axe. So it is intended for AS to select them. If you wish to force use of no tool, add this on a new line in `autoswitchAttackAction.cfg`: `minecraft!bamboo = `. The same would need to be done for bamboo shoots.

Leaves seem to be broken, I'll look into it. They should prefer shears and hoes.

Haybales will also need to be investigated.

**Comment by wiktormalyska** [comment]
Okay ty. I will check if anything more is picked wrongly

**Comment by dexman545** [comment]
Will be releasing 7.0.1 to modrinth shortly, should fix haybales and leaves. This issue will be autoclosed at that time, feel free to reopen or make a new one if you find other issues.
